// Code generated by go-bindata. DO NOT EDIT.
// sources:
// 01_init_database.down.sql
// 01_init_database.up.sql
package migrations

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var __01_init_databaseDownSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x72\x09\xf2\x0f\x50\x08\x71\x74\xf2\x71\x55\xf0\x74\x53\x70\x8d\xf0\x0c\x0e\x09\x56\x48\x2e\x2d\x2a\x4e\x8d\x4f\x4c\x49\xc9\xcf\xb3\xe6\xc2\xa3\xa2\x28\x35\x27\x35\xb1\x38\xd5\x9a\x0b\x10\x00\x00\xff\xff\xd7\xd0\xf8\xf1\x46\x00\x00\x00")

func _01_init_databaseDownSqlBytes() ([]byte, error) {
	return bindataRead(
		__01_init_databaseDownSql,
		"01_init_database.down.sql",
	)
}

func _01_init_databaseDownSql() (*asset, error) {
	bytes, err := _01_init_databaseDownSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "01_init_database.down.sql", size: 70, mode: os.FileMode(420), modTime: time.Unix(1529317648, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var __01_init_databaseUpSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x84\x90\xc1\x6a\xc3\x30\x10\x44\xef\xfa\x8a\x39\xda\x90\x3f\xe8\xc9\x0d\xeb\x20\xea\x2a\x45\x51\x21\x39\x19\x61\x6d\x8b\xc0\x96\x40\x8e\x5a\xfa\xf7\x45\x85\x8a\xb8\x50\x72\xd3\x32\xbb\x33\x4f\x23\xf6\x9a\x3a\x43\x30\xdd\xe3\x40\x90\x3d\xd4\xd1\x80\xce\xf2\x64\x4e\x98\x72\x5a\x79\xb4\xce\xc5\x80\x46\x00\xde\x41\x2a\x43\x07\xd2\x78\xd1\xf2\xb9\xd3\x17\x3c\xd1\x65\x27\x80\x60\x17\x86\xa1\xb3\x29\x43\x4e\x73\x7d\xaf\x79\x59\x6c\xfa\xaa\xb3\x8b\x9f\x61\x8e\xd6\x4d\x31\x87\xeb\xaf\x9b\x68\x1f\x84\xb8\x0f\x92\x78\x66\xbb\xf2\x5f\x94\xb2\xa7\x5e\x87\xa1\xd8\xbf\xf9\x99\x37\x2c\x53\x62\x7b\x65\x37\xda\x1a\x76\x4b\xb8\xb9\x7d\xb7\x0b\x8f\x1f\x9c\x56\x1f\x43\xbd\xff\xf9\xfc\xf8\x4f\xda\x4d\x09\x68\xbc\xdb\xd5\xed\xb6\xa8\xfd\x51\x93\x3c\xa8\xa2\x36\x55\x80\xa6\x9e\x34\xa9\x3d\x6d\xea\x6d\xbc\x6b\x4b\x0b\xdf\x01\x00\x00\xff\xff\xa3\xad\xc9\x9e\x8e\x01\x00\x00")

func _01_init_databaseUpSqlBytes() ([]byte, error) {
	return bindataRead(
		__01_init_databaseUpSql,
		"01_init_database.up.sql",
	)
}

func _01_init_databaseUpSql() (*asset, error) {
	bytes, err := _01_init_databaseUpSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "01_init_database.up.sql", size: 398, mode: os.FileMode(420), modTime: time.Unix(1529455085, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"01_init_database.down.sql": _01_init_databaseDownSql,
	"01_init_database.up.sql": _01_init_databaseUpSql,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"01_init_database.down.sql": &bintree{_01_init_databaseDownSql, map[string]*bintree{}},
	"01_init_database.up.sql": &bintree{_01_init_databaseUpSql, map[string]*bintree{}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

